### ISSUE TITLE
Resource temporarily unavailable

### ISSUE THREAD

**Issue by abhilashkariyappa** [kofemann/nfstest#1]
hitting this issue each time i run it on a share 

[root@RHEL67_base test]# ./nfstest_io -d /mnt/nfstest1/ -v info -n 10 -r 100 -e
INFO: 2017-03-01 01:54:33.441833  System:  Linux RHEL67_base 2.6.32-573.18.1.el6.x86_64 #1 SMP Wed Jan 6 11:20:49 EST 2016 x86_64
INFO: 2017-03-01 01:54:33.442131  Command: ./nfstest_io -d /mnt/nfstest1/ -v info -n 10 -r 100 -e
INFO: 2017-03-01 01:54:33.442184  SEED = 1488351273441
INFO: 2017-03-01 01:54:33.479084  10.244.84.107:/nfstest1/ mounted on /mnt/nfstest1
INFO: 2017-03-01 01:54:33.479377  NFS mount options: rw,vers=4,rsize=262144,wsize=262144,namlen=255,acregmin=3,acregmax=60,acdirmin=30,acdirmax=60,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=10.244.118.163,minorversion=0,local_lock=none
INFO: 2017-03-01 01:55:48.762294  ERROR on file object /mnt/nfstest1/f08000128 (process #8)
      Directory i-node: 2
      Traceback (most recent call last):
        File "/mora-nfstest/nfstest/file_io.py", line 982, in run_process
          self._do_file()
        File "/mora-nfstest/nfstest/file_io.py", line 905, in _do_file
          os.close(fd)
      OSError: [Errno 11] Resource temporarily unavailable

INFO: 2017-03-01 01:55:48.864861  ==================STATS===================
INFO: 2017-03-01 01:55:48.864990  OPEN:      25287
INFO: 2017-03-01 01:55:48.865067  OPENDGR:     216
INFO: 2017-03-01 01:55:48.865120  CLOSE:     25492
INFO: 2017-03-01 01:55:48.865184  OSYNC:      1577
INFO: 2017-03-01 01:55:48.865231  READ:     283487,   16.70 GB,  226.79 MB/s
INFO: 2017-03-01 01:55:48.865268  WRITE:    260248,   15.40 GB,  209.10 MB/s
INFO: 2017-03-01 01:55:48.865303  FSYNC:      5095
INFO: 2017-03-01 01:55:48.865334  RENAME:     1371
INFO: 2017-03-01 01:55:48.865366  REMOVE:     1337
INFO: 2017-03-01 01:55:48.865398  TRUNC:       542
INFO: 2017-03-01 01:55:48.865430  FTRUNC:      307
INFO: 2017-03-01 01:55:48.865461  LINK:        263
INFO: 2017-03-01 01:55:48.865492  SLINK:        51
INFO: 2017-03-01 01:55:48.865566  READDIR:     117
INFO: 2017-03-01 01:55:48.865601  LOCK:      56435
INFO: 2017-03-01 01:55:48.865633  TLOCK:     11299
INFO: 2017-03-01 01:55:48.865664  UNLOCK:    45224
INFO: 2017-03-01 01:55:48.865695  ERRORS:        1
INFO: 2017-03-01 01:55:48.865734  TIME:         75 secs

**Comment by kofemann** [comment]
looks like OS error, or server returns ERR_RESOURCE. Do you see something on the wire?

**Comment by abhilashkariyappa** [comment]
wire? i did not get you . works fine when used NFS version 3 .
